### ISSUE TITLE
Configure automated release notes

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/node-sdk#19]
## Objective

Automatically create release notes after publishing to NPM.

## Solution

A yaml file can be added to  `.github/release.yml` with the following content:

```yml
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Enhancements
      labels:
        - enhancement
    - title: Bugfixes
      labels:
        - bug
    - title: Other changes
      labels:
        - "*"
```

> NOTE: Labels can be adjusted to our use case.

## Resources

https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
